### ISSUE TITLE
Description: append() takes exactly one argument (0 given)  

### ISSUE THREAD

**Issue by zehrea** [scipion-em/scipion-em-cryocare#16]
Hello,

I generated even and odd tomograms using etomo outside of scipion3. I imported these tomograms into scipion3 to use in scipion's cryocare "prepare training data" tab. The GUI for "CryoCare prepare training data" asks only for even and odd volume and nothing else , which I provided. When I am trying to run the program, the run fails with the error below stating that an input is missing. What is this error?

Protocol validation failed. It usually happens because there are some input missing. Please check if the error message gives you any hint:
Error: TypeError 
Description: append() takes exactly one argument (0 given) 
Traceback:
  File "/usr/local/apps/scipion/3.0.11/mamba/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 2006, in validate
    childErrors = self._validate()

  File "/usr/local/apps/scipion/3.0.11/scipion-em-cryocare/cryocare/protocols/protocol_prepare_training_data.py", line 150, in _validate
    validateMsgs.append()

Thanks for your help,
Elena

**Comment by JorMaister** [comment]
Hi @zehrea,
First of all, my apologies for the late response. It won't happen again. Could you please execute the tests to check if everything is fine with the plugin installation? To do that execute scipion3 tests cryocare.tests.test_cryoCARE_workflow.TestCryoCARE
